/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'antousias' at '28/02/16 19:44' with Gradle 2.4
 *
 * @author antousias, @date 28/02/16 19:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
